FDA/open.fda.gov

- pages/about/index.md
> #97 updates to about page.

- pages/about/index.md
> #99 Updates to contributors section in About page

- pages/food/enforcement/_content.yaml
Copy paste mistake on Food recall page.
> FDA-73 food recall enforcement references device.

- package.json
- pages/device/510k/reference/_content.yaml
- pages/device/registrationlisting/_meta.yaml
Fixed a couple small bugs on the website, and adjusted the package.json slightly. Please verify that the new dev command works with your version of node by executing npm run dev.
> Fda 98/74 bug fixes

- .gitignore
- pages/api/_meta.yaml
- pages/api/reference/_content.yaml
- pages/blog/2015-07-23-drilling-into-the-details/index.md
- pages/blog/2015-08-06-new-release-coming-soon/index.md
- pages/blog/2015-12-23-openfda-now-allows-direct-downloads-of-data/index.md
- pages/device/510k/reference/_content.yaml
- pages/device/classification/reference/_content.yaml
- pages/device/event/reference/_content.yaml
- pages/drug/enforcement/reference/_content.yaml
- pages/drug/event/reference/_content.yaml
- pages/drug/label/reference/_content.yaml
- pages/food/enforcement/reference/_content.yaml
- pages/updates/index.jsx
Fixed the capitalization issues with openFDA/openfda/OpenFDA throughout the site.
> fda-101 Fixed the openFDA naming issues throughout the site.

- components/ApiStatus.jsx
- components/ApiUsage.jsx
Updates for the backend changes to the status component and some linter fixes in the Usage component.
> fda-141 Updated Status component and fixed linter issues in Usage component

- components/ApiUsage.jsx
- components/Downloads.jsx
- components/Nav.jsx
- components/SideBar/DownloadsMenu.jsx
- components/SideBar/index.jsx
- containers/DownloadsContainer.jsx
- package.json
- pages/api/statistics/index.jsx
- pages/downloads/_meta.yaml
- pages/downloads/index.jsx
Central download page for all endpoints.
> Fda 134 download page

- pages/api/reference/_content.yaml
- pages/api/reference/_fields.yaml
Updated api reference page to point to the new downloads page.
> fda-151 Updated api reference page.

- components/Nav.jsx
- containers/NavContainer.jsx
- css/_vars.styl
- css/components/Nav.styl
Also covers FDA-157, initial click on menu items not functioning.
> Fda 154 mobile menu

- pages/community/_apps.yaml
Commit message is inaccurate. Just added the link to the KnowRx app to the apps community page.
> fda-170 Added a new link to the Apps page

- README.md
Update instructions to correspond to `package.json` #156
> Update README.md (Fixes #156)

- package.json
Known moderate severity security vulnerability detected in marked < 0.3.18 defined in package.json
> FDA-50 Known moderate severity security vulnerability

- src/pages/apis/device/recall/_explorers.yaml
- src/pages/apis/drug/event/_infographic_definitions.json
Fixed typographic error on device API
> Fix Device Recall and AE Typos

- src/pages/apis/authentication/index.jsx
API URL Change in Authentication page.
> API URL Change in Authentication page.

- package.json
FDA-84 Address security alert in the front end repo.
> FDA-84 Address security alert in the front end repo.

- .gitignore
- .travis.yml
- package-lock.json
FDA-88 Add Travis CI config to the open.fda.gov GitHub repo to do basic checks
> FDA-88 Add Travis CI config to the open.fda.gov GitHub repo to do basic checks

- src/components/ApiUsage.jsx
Added "Dataset Downloads" stats section to the Usage page.
> Added "Dataset Downloads" stats section to the Usage page.

- src/components/DocSidebar.jsx
FDA-134 Left side nav highlights the item user is currently on.
> FDA-134 Left side nav highlights the item user is currently on

- src/components/FieldDownload.jsx
> FDA-201 Fix fields reference download buttons.

- package-lock.json
- package.json
- src/components/ApiUsage.jsx
- src/css/components/APIUsage.styl
- src/pages/about/statistics/index.jsx
FDA-207 Rework API Usage Component.
@beardedfinch, Please review and let me know if there are any changes that need to do.
> FDA-207 Rework API Usage Component.

- src/pages/apis/_explorers.yaml
- src/pages/apis/doc-links.yaml
- src/pages/apis/wildcard-search/index.jsx
Added `Wildcard search` page. Wildcard queries return documents that contain terms matching a wildcard pattern.
> Added `Wildcard search` page.

- src/components/ApiUsage.jsx
- src/pages/about/statistics/_content.yaml
Updated monthly API usage for July
> API usage update- July 1st

- src/components/ApiUsage.jsx
- src/pages/about/statistics/_content.yaml
This PR updates the API usage for October.
> API usage update for the month of October.
